FROM python:3.10-slim

WORKDIR /mlflow

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mlflow==3.3.2

EXPOSE 5000

